### ISSUE TITLE
  FlutterForegroundService.stop() is bad!

### ISSUE THREAD

**Issue by weiyinqing** [pspgt/flutter_foreground_service#1]

**Comment by Zeruel92** [comment]
Hi thanks for opening this issue, can you please provide a more complete feedback on what your seeing? Android Version, some logcat, what is the problem / error ?
Also note this plugin is really in an experimental phase and doesn't have all functionality working properly, I really appreciate some more info for improving the plugin itself

**Comment by weiyinqing** [comment]
issues：FlutterForegroundService.stop()不能停止服务

解决方法：我修改后的代码是：
@Override
    public void onDestroy() {
        
        Log.e("deletestop","stop");
        stopForeground(true);
        t.stop();
        stopSelf();
        super.onDestroy();
    }

然后问题就解决了！

**Comment by Zeruel92** [comment]
I'm sorry i can't understand what you wrote, can you speak english?

**Comment by Zeruel92** [comment]
added fix on commit 58e4a5e
