### ISSUE TITLE
When the flutter SDK is updated to v1.9.1 + hotfix.2, the plug-in prompts: “setBackgroundFlutterView tried to overwrite an existing FlutterNativeView” error？

### ISSUE THREAD

**Issue by weiyinqing** [pspgt/flutter_foreground_service#2]
Detailed questions：
E/AndroidRuntime(11148): FATAL EXCEPTION: Thread-3
E/AndroidRuntime(11148): Process: com.app.datacitymange, PID: 11148
E/AndroidRuntime(11148): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-3
E/AndroidRuntime(11148):        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
E/AndroidRuntime(11148):        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:697)
E/AndroidRuntime(11148):        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime(11148):        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:187)
E/AndroidRuntime(11148):        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:128)
E/AndroidRuntime(11148):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(11148):        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(11148):        at it.zeruel.flutter_foreground_service.ThreadRunner.run(ThreadRunner.java:62)
E/AndroidRuntime(11148):        at java.lang.Thread.run(Thread.java:764)
D/RenderingThreads(11148): Stopped rendering threads
E/Foreground(11148): setBackgroundFlutterView tried to overwrite an existing FlutterNativeView
W/zygote64(11148): Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?

to App flash back

**Comment by Zeruel92** [comment]
yeah i'm already aware of that issue, but currently i don't have time to investigate or trying to fix this issue. Also this repository is an experiment so it isn't inteded for production use. If you find a solution to this problem feel free to submit a pull request

**Comment by weiyinqing** [comment]
Hi，I found a solution！
This is my modified code，I hope you can correct this mistake and release it. Thank you.

@Override
    public void run() {
        while(running){
            try {
                this.t.sleep(this.timeout);
                Message message = new Message();
                message.what = 1;
                handler.sendMessage(message);
                //ForegroundService.backgroundChannel.invokeMethod("trigger",arg);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    public boolean setBackgroundFlutterView(FlutterNativeView view) {
        if (sBackgroundFlutterView != null && sBackgroundFlutterView != view) {
            Log.i("Foreground", "setBackgroundFlutterView tried to overwrite an existing FlutterNativeView");
            return false;
        }
        sBackgroundFlutterView = view;
        return true;
    }

    Handler handler = new Handler(){
        @Override
        public void handleMessage(Message msg) {
            Log.e("this is hander message",msg.what+"_____________________________");
            ForegroundService.backgroundChannel.invokeMethod("trigger",arg);
        }
    };

**Comment by Zeruel92** [comment]
thanks I'll check it as soon as possible

**Comment by Zeruel92** [comment]
i tried your code seems work fine, fix is on commit 58e4a5e
